name: Test Build (No Release)

on:
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        with:
          # We don't provide a releaseId, so it won't publish a GitHub Release
          args: ''

      - name: Upload Windows MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: padsphere-windows-test-installer
          path: src-tauri/target/release/bundle/msi/*.msi
